import type { Story } from "./stories";
import { TOKEN_PRICE, LANGUAGES_LINE } from "@/config/site";

/** Journal expansion (2026-07-06): 10 articles from live keyword research
 *  (Google autocomplete, India locale; question-form clusters). Useful-first,
 *  scene-first, voice-linted. Product mentions stay soft or absent. */

export const EXPANSION: Story[] = [
  {
    slug: "how-much-screen-time-for-a-3-to-6-year-old",
    title: "How much screen time is okay for a young child?",
    description:
      "How much screen time is okay at two, three, four or five? The WHO, Indian Academy of Pediatrics and AAP numbers, what the hour is for, and what to do at 6pm.",
    theme: "Screen-free living",
    author: "Kashyap C.R",
    published: "2026-07-28",
    updated: "2026-09-05",
    pose: "curious",
    tint: "bg-blue/15",
    hero: "/stories/how-much-screen-time-for-a-3-to-6-year-old.jpg",
    heroAlt:
      "A mother and her young child laughing over wooden blocks in the evening while the TV stays dark",
    paragraphs: [
      { p: "For ages two to four, the World Health Organization says no more than one hour of sedentary screen time a day, and less is better. The Indian Academy of Pediatrics says the same for two to five, supervised, and under two hours from five to ten. Under two: none. That is the number. The rest is what the hour is for." },
      { p: "Every parent has googled this at some point, usually at 9pm, usually after a day when the tablet did more babysitting than planned. So the number comes first, and the useful part comes after it." },
      { h: "What do the guidelines say, age by age?", p: "The [WHO guideline](https://www.ncbi.nlm.nih.gov/books/NBK541169/) from 2019 is the one most others lean on. Under one year: no screen time. At one: none. At two: no more than one hour, and less is better. At three and four: no more than one hour, and less is better. The [Indian Academy of Pediatrics](https://pubmed.ncbi.nlm.nih.gov/34969943/) wrote its own guidance in 2022, for Indian homes, and it lines up: no screens below two years, at most one hour of supervised screen time a day from two to five, and under two hours a day from five to ten. The [American Academy of Pediatrics](https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds) says about an hour a day of high-quality programmes for ages two to five, watched together, and a video call with family is the one exception it makes for the very young." },
      { h: "Why is the number the small half of the advice?", p: "Read those documents closely and you notice something. All three spend less ink on the hour and more on what the hour replaces. The real worry is not the screen. It is the sleep, the play, the running, and above all the talking that a screen quietly eats. An hour of cartoons in a day full of conversation is a different thing from an hour of cartoons in a day of silence. The guideline is a fence. The field inside it is language." },
      { p: "There is research behind that last sentence. A [2018 study](https://pmc.ncbi.nlm.nih.gov/articles/PMC5945324/) recorded the home language of 36 children aged four to six, then watched their brains work while they listened to a story. The children who had more back-and-forth conversation with adults showed more activity in the brain's language region, and that held whatever the family's income and however many words the child simply overheard. The turns mattered, not the volume." },
      { h: "Does it matter what they watch?", p: "Yes, and the AAP is specific about it. Slow, simple programmes beat fast ones, because young children cannot follow quick cuts and learn less from them. Apps stuffed with distracting extras teach less than plain ones. Anything violent is out. And the biggest single lever is the cheapest: sit with them. A child who watches beside a parent who talks about what is on the screen gets something closer to a conversation than to a screen." },
      { h: "What about the hour before bed?", p: "Keep it screen-free. The AAP asks for no screens in the hour before bedtime and none in the bedroom, and sleep is when the day's learning gets filed away. If the evening routine leans on a screen to wind down, move the screen earlier and put a story, a song or a bath in its place. It takes about a week to feel normal." },
      { h: "What do you actually do at 6pm?", p: "Knowing the number does not cook dinner. A few things that work in real houses: pick the screen window in advance and tell your child when it ends, so the end is not a surprise. Put something after it that they like, so the end is a beginning. Keep the screen in the shared room, not the bedroom. And when you can, sit with them for a few minutes of it and talk." },
      { p: "If the evening still collapses without a screen, you do not need more discipline. You need a better alternative. Something that answers back." },
      { p: "That is the gap we are building [Kheelu](/products/kheelu) for: a screen-free friend that talks, in the languages you speak at home. But screen or no screen, the hour is yours to place. The talking is the part that cannot be skipped. If you want the named rules parents pass around, and which ones have evidence behind them, [that read is here](/stories/screen-time-rules-parents-swear-by)." },
    ],
    sources: [
      { label: "World Health Organization: Guidelines on physical activity, sedentary behaviour and sleep for children under 5 years of age (2019)", url: "https://www.ncbi.nlm.nih.gov/books/NBK541169/" },
      { label: "Indian Academy of Pediatrics: Guidelines on screen time and digital wellness in infants, children and adolescents (Indian Pediatrics, 2022)", url: "https://pubmed.ncbi.nlm.nih.gov/34969943/" },
      { label: "The same IAP guidelines, full text (Indian Pediatrics, March 2022, PDF)", url: "https://www.indianpediatrics.net/mar2022/235.pdf" },
      { label: "American Academy of Pediatrics: Media and Young Minds, policy statement (Pediatrics, 2016)", url: "https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds" },
      { label: "Romeo and colleagues: Beyond the 30-Million-Word Gap, children's conversational exposure and language-related brain function (Psychological Science, 2018)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5945324/" },
    ],
  },
  {
    slug: "screen-time-and-tantrums",
    title: "Screen time and tantrums: what is actually happening",
    description:
      "Why the meltdown lands the moment the screen goes off, and how to make switching off boring instead of explosive.",
    theme: "Screen-free living",
    author: "Kashyap C.R",
    published: "2026-07-28",
    updated: "2026-07-31",
    pose: "grumpy",
    tint: "bg-orange/15",
    hero: "/stories/screen-time-and-tantrums.jpg",
    heroAlt:
      "A small child crying on the living room rug while his mother kneels beside him, calm and open-armed",
    paragraphs: [
      { p: "The video ends. You say that is enough for today. And a child who was silent for forty minutes becomes a small weather system on your living room floor." },
      { p: "If this is your house some evenings, it is most houses some evenings. The tantrum after the screen is so common it has its own research literature. Knowing the mechanics helps." },
      { h: "Why the meltdown comes at the off switch", p: "Fast, bright, always-rewarding video sets a pace no living room can match. When it stops, everything real feels slow and dim by comparison, and a three year old does not have the brakes to manage that drop. The tantrum is not defiance. It is a small brain being asked to change gears at highway speed." },
      { p: "This is also why the second video is easier to grant than the first was. Each yes resets the peak, and the fall gets steeper." },
      { h: "Making the off switch boring", p: "The trick that works is not a firmer no. It is a softer landing. End the screen at a natural break, not mid-episode. Announce the landing before takeoff: one episode, then we water the plants together. And give the hands somewhere to go the moment the screen goes dark, because empty hands go looking for the remote." },
      { p: "Notice the pattern in all three: the exit needs somewhere to arrive. Children leave screens easily for things that want them back." },
      { p: "A voice that listens is one of those things. It does not flash or score points. It just answers, and asks, and waits. Calm holds attention longer than parents expect, and it hands attention back gently. That idea is the reason our little talking friend exists, but it works with a grandparent on the phone too." },
    ],
  },
  {
    slug: "the-gentle-way-off-the-phone",
    title: "The gentle way off the phone: a seven-day plan",
    description:
      "A realistic week-long plan to reduce a young child's screen time without turning your home into a battlefield.",
    theme: "Screen-free living",
    author: "Kashyap C.R",
    published: "2026-07-28",
    updated: "2026-07-31",
    pose: "bliss",
    tint: "bg-yellow/15",
    hero: "/stories/the-gentle-way-off-the-phone.jpg",
    heroAlt:
      "A parent's hand placing a phone into a wooden drawer while a child builds a block tower in the background",
    paragraphs: [
      { p: "Nobody plans for their four year old to know exactly where the YouTube app lives. It happens one busy evening at a time, and then one day the phone is the first thing they ask for and the last thing they give up." },
      { p: "Going cold turkey usually fails, because the phone was solving real problems: your meeting, their boredom, the queue at the clinic. Take it away without replacing what it did and the house pays. So here is a week that replaces before it removes." },
      { h: "Days one and two: just watch", p: "Change nothing yet. Notice when the phone appears. Morning rush? The cooking hour? The car? Each slot is a problem the phone got hired to solve. Write them down. You will usually find two or three, not ten." },
      { h: "Days three and four: replace the easiest slot", p: "Pick the slot where the stakes are lowest and put something in it that talks or moves: audio stories in your language, a cousin on a voice call, a puzzle you started together at breakfast so it is waiting for them. Keep the hard slots untouched. One win matters more than three fights." },
      { h: "Days five and six: shrink, do not snatch", p: "In the remaining slots, end the screen at natural breaks and land it somewhere: a job, a snack, a who-can-spot-a-crow contest at the window. The plan from our tantrums article applies here on repeat." },
      { h: "Day seven: make the new normal visible", p: "Tell your child what changed, in their language: mornings are for songs now, the car is for spotting autos. Children accept rules they can predict far better than moods they cannot." },
      { p: "Expect a wobbly week two, and expect it to pass. What stays is the discovery underneath: most of what the phone was providing was a voice paying attention. Provide that, from anyone or anything that genuinely listens, and the phone loses its main job." },
    ],
  },
  {
    slug: "how-to-get-your-child-talking",
    title: "How to get your child talking",
    description:
      "Better questions than 'how was school', and the small habits that turn one-word answers into real conversations.",
    theme: "Talking together",
    author: "Ria Mangala Rewari",
    published: "2026-07-28",
    updated: "2026-09-05",
    pose: "joy",
    tint: "bg-blue/15",
    hero: "/stories/how-to-get-your-child-talking.jpg",
    heroAlt:
      "A child standing at the family dinner table, arms wide mid-story, while his parents lean in laughing",
    paragraphs: [
      { p: "How was school? Fine. What did you do? Nothing. Two questions in, the conversation is over, and the child who narrated every ant on the footpath at age three has become a vault at five." },
      { p: "The vault is rarely about you. Broad questions are genuinely hard to answer. A whole day is too big to summarize, so children reach for the smallest true word they have. Fine." },
      { h: "Ask smaller, get bigger", p: "Swap the summary question for a specific one. Who made someone laugh today? What was the worst thing on your plate at lunch? If your classroom had a door to anywhere, where did it go today? Specific questions are easier to enter and more fun to answer, and one good answer usually brings friends." },
      { p: "Two more habits do quiet magic. Answer the question yourself first: the worst thing on my plate was the office canteen dal, and here is why. Children join conversations more easily than they start them. And leave gaps. A count of five feels like an hour, but the gap is where children decide to fill." },
      { h: "The follow-up is the whole game", p: "Whatever comes back, chase it one step. Not with a quiz, with curiosity. He fell off the bench? What did the teacher do? Then what did you do? The follow-up tells your child that their answer went somewhere, and answers that go somewhere get longer." },
      { p: "This serve and return pattern is the same mechanism researchers keep finding at the center of language growth. We wrote about the science of it in another piece. The kitchen version is simpler: ask small, answer first, wait long, follow up." },
      { p: "And on the evenings you cannot be the asker, any patient voice helps keep the muscle warm. That is the job we gave Kheelu: ask, listen, ask again. The dinner table stays yours." },
    ],
  },
  {
    slug: "talking-late-or-talking-little",
    title: "Talking late, or talking little?",
    description:
      "A calm guide for parents of quiet 3 and 4 year olds: what varies normally, what deserves a professional look, and what helps at home either way.",
    theme: "Talking together",
    author: "Ria Mangala Rewari",
    published: "2026-07-28",
    updated: "2026-07-31",
    pose: "sad",
    tint: "bg-orange/15",
    hero: "/stories/talking-late-or-talking-little.jpg",
    heroAlt:
      "A father and his young daughter share a picture book on a window seat, her finger resting on a page, morning light behind them",
    paragraphs: [
      { p: "Somewhere at every birthday party there is a parent doing quiet math: that child is narrating a whole movie, mine points and says come. Is this fine? Is this something?" },
      { p: "First, the honest frame. Children spread themselves across a wide normal range, late talkers often catch up completely, and quiet is a temperament as well as a milestone. Also true: some children need help, earlier help works better, and a parent's gut feeling is real information." },
      { h: "When to ask a professional", p: "This article is not a diagnosis, and no article is. As a general guide, talk to your pediatrician or a speech-language professional if your child says very few words by two and a half, is hard for family to understand at three, loses words they used to have at any age, or seems not to understand simple things you say. If your gut says ask, ask. The worst case of asking early is reassurance." },
      { h: "What helps at home, either way", p: "Whether your child is a late bloomer or just an economist with words, the home game is the same. Narrate your day out loud while you do it: the dal is boiling, now the pressure cooker, one whistle, two. Give choices instead of yes-no questions, because red cup or yellow cup demands a word. Read the same book the tenth time without sighing, since repetition is how words set." },
      { p: "Above all, respond to every attempt as if it were a sentence. A point, a sound, a half-word: answer it fully. Children speak more where speaking works." },
      { p: "One caution from us, and it applies to our own product too: no toy replaces a professional when one is needed, and no toy replaces you. Talking toys, songs, and story audio can add more chances to hear and answer language at home. Think of them as extra rounds of practice, never as the coach." },
    ],
  },
  {
    slug: "what-actually-builds-a-sharp-brain",
    title: "What actually builds a sharp brain in the early years",
    description:
      "Past the flashcards and brain-training claims: the four everyday things research keeps pointing at, and how to get more of them.",
    theme: "How children grow",
    author: "Apoorva Sahu",
    published: "2026-07-28",
    updated: "2026-07-31",
    pose: "curious",
    tint: "bg-blue/15",
    hero: "/stories/what-actually-builds-a-sharp-brain.jpg",
    heroAlt:
      "A young boy on a stool drops peas into a steel bowl mid-chat while his mother stirs a pot beside him",
    paragraphs: [
      { p: "Type how to make my child's brain sharp into any search box and an industry answers: apps, flashcards, tonics, courses for three year olds. The volume of it can make an ordinary home feel like not enough." },
      { p: "Here is the comforting, slightly boring truth. The things that build a young brain are old things. Research keeps circling the same four." },
      /* The "aged 3 to 6" below is SOURCED sleep guidance, not our audience
         range. Age passes moved product-facing copy (now 2 to 5 / 2 to 14), but a cited
         age band keeps its real numbers (never-invent-claims). */
      { h: "Conversation, sleep, play, and calm", p: "Conversation, especially the back and forth kind, builds language and thinking at once; researchers count conversational turns, not vocabulary drills. Sleep is when the day's learning gets filed, and children aged 3 to 6 need ten to thirteen hours of it. Play, the unstructured kind where the sofa becomes a ship, is where planning, memory, and self-control get their reps. And a calm, warm home is not a luxury: chronic stress is one of the few things reliably shown to work against a growing brain." },
      { p: "Notice what is not on the list. There is no app on it. Educational toys and brain development toys can help, but only the ones that produce more of the four: a toy that starts a conversation earns its place, a toy that performs at your child does not." },
      { h: "The dinner-table test", p: "A useful filter for anything sold as brain-building: after ten minutes with it, does your child have something to say? Blocks pass the test. A good story passes. A cartoon marathon mostly fails. Judge our talking toy with the same test, and judge everything else with it too." },
      { p: "The families doing this best are not buying more. They are talking more, sleeping on time, leaving room for nonsense games, and keeping the volume of the house low. Sharp grows in that soil." },
    ],
  },
  {
    slug: "how-children-collect-words",
    title: "How children collect words",
    description:
      "Vocabulary is not memorized, it is collected. How children pick up words at home, in any language, without a single worksheet.",
    theme: "Talking together",
    author: "Ria Mangala Rewari",
    published: "2026-07-28",
    updated: "2026-07-31",
    pose: "silly",
    tint: "bg-yellow/15",
    hero: "/stories/how-children-collect-words.jpg",
    heroAlt:
      "A father carries his daughter through a vegetable market at golden hour as she points at something for him to name",
    paragraphs: [
      { p: "Nobody taught your child the word auto. Or gravy, or cousin, or the slightly alarming place they learned whatever they said last Tuesday. Words arrive like sand in beach clothes: constantly, invisibly, from everywhere." },
      { p: "Between three and six the collection explodes. Many children add words at a pace that works out to several a day, every day, for years. The question is not how to make a child memorize words. It is how to stand in the sandstorm." },
      { h: "Words stick to feelings and use", p: "Two rules govern which words stay. Words heard in moments that matter stick better than words from lists: paltan learned at a wedding beats any flashcard. And words a child gets to use survive, while words only heard fade. A new word needs a job within a day or two of arriving." },
      { p: "So the home program is simple. Use your good words out loud instead of simplifying everything down. When a big word lands, hand it back in a question: it was chaotic? What was the most chaotic part? And let your child overhear real adult conversation, which has always been the original vocabulary app." },
      { h: "Any language counts", p: "One more thing, because parents in India carry a special worry here: words collected in Telugu or Bangla or Marathi count fully. The brain does not file languages in separate purses that empty each other. A child rich in home-language words has a head start on words in every language after." },
      { p: "Keep the house full of talk worth stealing from. The collection builds itself." },
    ],
  },
  {
    slug: "raising-a-bilingual-child-in-india",
    title: "Raising a bilingual child in India",
    description:
      "Does a bilingual home confuse a young child? What the research says about two languages, why the mother tongue is the one at risk, and what keeps it alive.",
    theme: "Languages at home",
    author: "Ria Mangala Rewari",
    published: "2026-07-28",
    updated: "2026-09-05",
    pose: "joy",
    tint: "bg-blue/15",
    hero: "/stories/raising-a-bilingual-child-in-india.jpg",
    heroAlt:
      "A grandmother braids her granddaughter's hair on a sunlit courtyard step, both mid-song, a plate of jasmine beside them",
    paragraphs: [
      { p: "Raising a bilingual child in India does not confuse them, delay their speech or cost them English. Children who grow up with two languages know about as many words in total as children with one, mixing languages is a normal stage, and the mother tongue is the foundation the second language is built on, not its competitor." },
      { p: "There is a moment many Indian parents know: your child answers your Kannada in English, and something in you notes it, half proud, half strangely sad. The pride makes sense. English opens doors here, and every parent knows which exams and interviews wait down the road. But the quiet maths many families do, that home language time is time stolen from English, has the research exactly backwards." },
      { h: "Does a second language confuse or delay a young child?", p: "No. A [2013 review of the research](https://pmc.ncbi.nlm.nih.gov/articles/PMC6168212/) on bilingual children, written for parents and teachers by two developmental psychologists, is blunt about it: bilingual children are not more likely than monolingual children to have difficulties with language, to show delays in learning, or to be diagnosed with a language disorder. They may know fewer words in each language on its own, which is what a worried parent notices. Add the two lists together and the total matches a child growing up with one language. A child who says paani at home and water at school has two words for one idea, and that is a gain, not a gap." },
      { h: "Is mixing the two languages a problem?", p: "It is a stage, and a clever one. The same review notes that even two-year-olds adjust which language they use to the person they are speaking to. Mixing inside a sentence, the paani-in-the-glass kind, is a child using everything they have, and it fades as each language fills out. Correcting it teaches a child that one of their languages is wrong. Answering warmly in your own language teaches them that both are welcome." },
      { h: "Why is the mother tongue the one at risk?", p: "In most Indian homes, English has school, screens and half the world working for it already. It does not need your kitchen too. The language that needs your kitchen is the one only your family can pass on. Concepts learned in the mother tongue transfer: a child who understands big and small, before and after, why and because in Tamil does not relearn those ideas in English. They relabel them, which is far faster. That is why India's own [National Education Policy 2020](https://www.pib.gov.in/PressReleasePage.aspx?PRID=1847061&reg=48&lang=2) asks schools, wherever possible, to teach in the home language or mother tongue until at least Grade 5 and preferably until Grade 8. The policy rests on the same idea: children learn best in a language they already understand." },
      { h: "What keeps a home language alive?", p: "Children keep languages that are useful and loved, and drop languages that are neither. So give the language living jobs: the funny relatives, the food words, the songs, the one grandparent whose stories only exist in it. Speak it without apology. When your child answers in English, answer back in your language without making it a correction. Read in it, even if you have to hunt for the books. Let it carry the good moments, not only the instructions. The war is lost in the moment the language becomes homework." },
      { p: "One more thing helps more than any rule: conversation, in whichever language is flowing. Researchers at Harvard describe how children learn as [serve and return](https://developingchild.harvard.edu/key-concept/serve-and-return/), a child offering a word or a question and an adult returning it. The loop works in Bengali exactly as well as in English, and a child who gets more turns gets more language." },
      { h: "Who speaks what, day to day?", p: "Families make this work in several shapes, and none of them is the rule. Some pick one language per parent. Some keep one language for home and let school carry English. Some let the grandparents own the mother tongue. What the shapes share is a pattern a child can predict and warmth a child can feel. Pick the one your household can actually keep, and change it when life changes." },
      { p: `We are building for exactly these houses. [Kheelu](/products/kheelu) speaks ${LANGUAGES_LINE}, with up to ten languages at launch, so the friend can meet your family where it lives rather than drag it toward English. But with or without any toy, the principle holds: the mother tongue is not in the way of your child's future. It is under it.` },
    ],
    sources: [
      { label: "Byers-Heinlein and Lew-Williams: Bilingualism in the early years, what the science says (LEARNing Landscapes, 2013, via PubMed Central)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6168212/" },
      { label: "Government of India, Press Information Bureau: Education in mother tongue under the National Education Policy 2020, paragraph 4.11 (2022)", url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=1847061&reg=48&lang=2" },
      { label: "Harvard University, Center on the Developing Child: Serve and return", url: "https://developingchild.harvard.edu/key-concept/serve-and-return/" },
    ],
  },
  {
    slug: "should-kids-use-ai",
    title: "Should kids use AI? An honest answer from people who build it",
    description:
      "Should kids use AI? We build it for children and would not hand a chatbot to a four-year-old. Where the line is, and how to judge any toy with AI inside.",
    theme: "AI and childhood",
    author: "Aman Soni",
    published: "2026-07-28",
    updated: "2026-09-05",
    pose: "grumpy",
    tint: "bg-orange/15",
    hero: "/stories/should-kids-use-ai.jpg",
    heroAlt:
      "A father with his son on his lap points at a laptop screen while the boy follows his finger, lamp-lit and side by side",
    paragraphs: [
      { p: "No, not the AI most people mean by the word: chatbots and apps built for adults, open to the whole internet, engineered to keep a user engaged. We build AI for children and would not hand one of those to a four-year-old. The useful question is narrower: what does a tool with AI inside do to the hours it fills?" },
      { p: "We should be the last people to ask, or the first. Either way, our honest answer is one most AI companies will not give you, so here it is in full." },
      { h: "Why is the AI in the news the wrong kind for a child?", p: "The chatbots and apps making headlines were built for adults. They will talk about anything, they are wrong with total confidence, they are designed to keep a user in the conversation, and they will happily fill the hours a childhood is supposed to spend elsewhere. Handing one to a four-year-old is handing over the open internet with a friendlier face. That is not a hunch. When [Common Sense Media](https://institute.commonsensemedia.org/risk-assessments/ai-toys) tested AI toy companions in January 2026, more than a quarter of the replies its testers logged included content a child should not hear, from self-harm to drugs. Its conclusion was that no child of five or under should be given one. [Fairplay](https://fairplayforkids.org/ai-toys-unsafe-for-kids-this-holiday-season-advisory-warns/) and more than 150 experts went further in November 2025 and told parents not to buy AI toys at all." },
      { h: "So why do we build one?", p: "Because the question hiding inside the question is about design, not about AI. Notice what the warnings are actually afraid of: unlimited content, no adult in the loop, engagement without end, a machine that talks at a child rather than with them, and a toy that pretends to be alive. Every one of those is a choice. Which means every one of them can be designed out, and a company that refuses to design them out is telling you what it values." },
      { p: "A tool with AI inside can be built the opposite way: a closed library instead of the open internet, answers filtered for the age of the listener, a parent who can read every word and delete any of it, no feed, no points, no streaks, and no reason to stay one minute past the fun. It can be a toy that answers a question and then asks one back, so the child does the talking. At that point the question stops being should kids use AI and becomes the question you ask about any toy: what does it do to the hours it fills?" },
      { h: "What does the research say children actually need?", p: "The same thing it has said for decades: back-and-forth conversation with a person who answers. The [American Academy of Pediatrics](https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds) asks parents of two to five year olds to keep screens to about an hour of good content a day and to watch together, because a young child learns from media mostly when an adult talks about it with them. Researchers at Harvard call the loop underneath all of this [serve and return](https://developingchild.harvard.edu/key-concept/serve-and-return/): the child offers a sound, a look or a question, and an adult returns it. A toy earns its place only if it produces more of that loop, not less. A toy that performs at your child while they watch is a screen without the picture." },
      { h: "How do you judge anything with AI inside?", p: "Five questions, whoever is selling, ours included. Can it reach the open internet? Is every response filtered for your child's age, and can the maker say how? Can you read the full history and delete it yourself? Does the company earn more when your child spends more minutes? And does it talk with your child, in questions and turns, or perform at them? Five good answers is a tool. Fewer is a slot machine with a cartoon on it." },
      { p: "Add one more for a toy that lives in a bedroom: when is the microphone on? The only good answer is when your child says a wake word, and off the rest of the time. Our longer checklist, with what India's data-protection law now requires of anyone holding a child's data, is [here](/stories/what-to-look-for-in-a-safe-ai-toy)." },
      { h: "Where does Kheelu stand?", p: "[Kheelu](/products/kheelu) is built for ages three and up on the opposite design: a closed library, no open internet, an age-graded safety layer on every reply, a full conversation log you can read and delete in the parent app, no ads, nothing sold, and a friend that asks the next question rather than filling the silence. Whether that is enough is your call to make, not ours to declare, and the child-safety groups above are right to make companies earn it. The mechanisms are on our [Safety page](/safety), in plain words, so you can check rather than trust." },
      { p: `AI near children is not a yes or no. It is a who built this and why. Ask that question loudly and often, and make every company answer it in plain words. Ours are on the Safety page, and if they earn your trust, a refundable ${TOKEN_PRICE} holds your place.` },
    ],
    sources: [
      { label: "Common Sense Media, Youth AI Safety Institute: AI Toys risk assessment (January 2026)", url: "https://institute.commonsensemedia.org/risk-assessments/ai-toys" },
      { label: "Common Sense Media: press release on the AI toy companion findings (22 January 2026)", url: "https://www.commonsensemedia.org/press-releases/common-sense-media-warns-against-ai-toy-companions-after-research-reveals-safety-risks" },
      { label: "Fairplay: AI toys are not safe for kids, advisory signed by more than 150 experts and organisations (20 November 2025)", url: "https://fairplayforkids.org/ai-toys-unsafe-for-kids-this-holiday-season-advisory-warns/" },
      { label: "American Academy of Pediatrics: Media and Young Minds, policy statement (Pediatrics, 2016)", url: "https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds" },
      { label: "Harvard University, Center on the Developing Child: Serve and return", url: "https://developingchild.harvard.edu/key-concept/serve-and-return/" },
    ],
  },
  {
    slug: "busy-hands-no-screens",
    title: "Busy hands, no screens",
    description:
      "Screen-free ways to keep a young child genuinely busy at home, including on the days you have to work.",
    theme: "Screen-free living",
    author: "Apoorva Sahu",
    published: "2026-07-28",
    updated: "2026-07-31",
    pose: "silly",
    tint: "bg-yellow/15",
    hero: "/stories/busy-hands-no-screens.jpg",
    heroAlt:
      "A young girl paints the balcony floor with water and a big brush while her mother works at the table inside, glancing over with a smile",
    paragraphs: [
      { p: "It is 4pm, your call starts in ten minutes, and a small person is orbiting your desk asking what they can do. The tablet would solve this in four seconds. That is exactly why it feels like cheating." },
      { p: "The screen-free answer is not one magic activity. It is understanding what the screen was providing: a task with no setup, no adult, and no way to fail. Anything with those three properties can compete." },
      { h: "The ten-second setups", p: "Keep a shelf of things that start instantly and end wherever: a bucket of water and a paintbrush to paint the balcony floor, a dabba of rajma to sort by wrinkles, old newspaper to tear into the world's largest salad, a blanket over two chairs that is a house until dinner. The humbler the material, the longer it lasts. Expensive toys have one script. A cardboard box has forty." },
      { h: "Jobs beat games", p: "The secret weapon of small children is that they do not yet know work is work. Being asked to match all the socks, wash the potatoes, or guard the dough while it rises is not a chore to a four year old. It is a promotion. Real jobs hold attention longer than invented games because children can smell the difference." },
      { p: "And for the stretches where you truly cannot be interrupted, line up company that talks: story audio in your language, a grandparent on speaker, a voice that asks questions back. Busy hands last longest when there is a voice keeping the mind company too. Building that voice is our whole project, but the shelf and the socks need no technology at all." },
      { p: "The house does not need to become a preschool. It needs six reliable boredom exits. Build the shelf once, and 4pm gets easier for a year." },
    ],
  },
  /* V4 additions (2026-07-30): five pieces against demand validated live in
     Google India (evidence per slug: docs/revamp-2026-07/keywords-v3.md).
     Same laws as the rest of the journal: useful-first, scene-first, no
     invented statistics, one soft invite at most. Heroes pending from the
     founder (gemini-handoff/feedback-round-2026-07/) — pose+tint carry the
     cards until then. */
  {
    slug: "does-a-three-year-old-need-an-ai-tutor",
    title: "Does a three-year-old need an AI tutor?",
    description:
      "Tutoring apps promise homework help. Your child cannot do homework yet. What an AI tutor should mean before school age.",
    theme: "AI and childhood",
    author: "Apoorva Sahu",
    published: "2026-07-30",
    updated: "2026-09-05",
    pose: "curious",
    tint: "bg-orange/15",
    hero: "/stories/does-a-three-year-old-need-an-ai-tutor.jpg",
    heroAlt:
      "A father listens, chin in hand, while his young daughter explains her tower of blocks across the coffee table",
    paragraphs: [
      { p: "Type AI tutor for kids into a search bar and you meet a wall of homework apps. Fraction practice, essay feedback, exam prep. All of it useful, and none of it built for a person who still needs help with shoe laces." },
      { p: "Yet the phrase keeps rising, and parents of much younger children are the ones typing it. The instinct underneath is sound. The years before school are when a child learns faster than they ever will again, and every parent quietly wonders whether they are doing enough with them." },
      { h: "What tutoring means at three", p: "A school tutor drills a syllabus. A three-year-old has no syllabus. What they have is questions, hundreds of them a day, and the research on early learning keeps arriving at the same place: children this age learn through back and forth conversation, not instruction. The tutor a three-year-old needs is a patient answerer who asks one question back." },
      { p: "Measured against that, most of what is sold as an AI tutor is simply the wrong tool. A screen-based app asks a small child to sit still, watch a display, and follow a curriculum. That is a classroom shrunk to phone size, and small children learn least that way." },
      { h: "What to look for instead", p: "If you are weighing AI tutoring for a child under five, look for four things. Voice first, because conversation is the skill being built. No screen, because the display adds nothing a small child needs. A pace set by the child, not by a lesson plan. And a full record you can read, because you should never wonder what a tutor said to your child." },
      { p: "Notice that none of those four is about a syllabus. At this age the syllabus is the conversation itself: words, numbers, feelings, and the endless why. A child who is heard keeps asking, and a child who keeps asking keeps learning." },
      { p: "There is one more honest answer to the question in the title: no, a three-year-old does not need an AI tutor. Children have grown up brilliantly for millennia without one. What a good one offers is more of the thing that already works, conversation, in the hours your own patience runs out." },
      { p: `That is the job we are building Kheelu for: a screen-free friend that answers, asks one back, and moves at your child's pace, in the languages you speak at home. If that sounds like the tutor you were actually searching for, pre-orders are open, and the ${TOKEN_PRICE} that holds your place is refundable until we ship.` },
    ],
  },
  {
    slug: "a-toy-that-talks-vs-a-toy-that-listens",
    title: "A toy that talks is not a toy that listens",
    description:
      "Talking toy or listening toy? Why a toy that repeats your child is a mirror, what serve and return does for a growing brain, and how the toy categories compare.",
    theme: "Talking together",
    author: "Aman Soni",
    published: "2026-07-30",
    updated: "2026-09-05",
    pose: "silly",
    tint: "bg-blue/15",
    hero: "/stories/a-toy-that-talks-vs-a-toy-that-listens.jpg",
    heroAlt:
      "A boy whispers a secret into a teddy bear's ear while battery-operated toys sit ignored on the shelf behind them",
    paragraphs: [
      { p: "A toy that talks plays or repeats sounds at your child. A toy that listens understands what your child said and answers it, then asks something back. The difference matters because children learn language through back-and-forth turns, and a toy that cannot return the turn cannot start one, however much noise it makes." },
      { p: "Walk down any toy aisle in India and the talking toys line up: a dancing cactus that records what your child says and squeaks it back, phrase-button phones, dolls with six sentences, plushes that sing on a squeeze. Children find them hilarious, for about a week. They all talk. Almost none of them listen." },
      { h: "Why does repeating run out?", p: "A toy that repeats gives your child their own words back. That is a mirror, and mirrors are entertaining, but they do not answer questions. Once the novelty fades there is nothing left to discover, which is why these toys migrate to the bottom of the basket by month two. A toy with six sentences runs out on day one. The child has simply heard them all." },
      { h: "What does listening actually do for a growing brain?", p: "Researchers at Harvard describe how children learn to talk as [serve and return](https://developingchild.harvard.edu/key-concept/serve-and-return/): the child serves a sound, a look or a question, and someone returns it with meaning and a new serve. It is the return that builds vocabulary, logic and confidence. A [2018 study](https://pmc.ncbi.nlm.nih.gov/articles/PMC5945324/) of 36 children aged four to six found that the number of conversational turns a child had with adults, not the number of words they overheard, tracked with activity in the brain's language region, whatever the family's income. A toy that only repeats never returns the serve. A toy that only performs never invites one." },
      { h: "Screens, speakers, talking toys, AI toys: how do they compare?", p: "Here is the honest map, category by category, before we get to our own." },
      { h: "Apps and tablets", p: "The richest content and the strongest pull. A cartoon can show your child a volcano, but it cannot pause when their eyes go wide and ask what happens next. The [American Academy of Pediatrics](https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds) asks for about an hour a day of good content for two to five year olds, watched together, because the learning happens in the talking about it, not in the watching. On its own, a screen is a performance." },
      { h: "Smart speakers", p: "They listen and answer, which is a real step up, but they were built for adults. They reach the open internet, they answer anything, and they are not filtered for a three-year-old. Useful for music and timers. Not a friend for a child to talk to alone." },
      { h: "Talking toys that repeat or play phrases", p: "Safe, simple, offline and cheap, and worth having for the giggle. They cannot answer a question they have never heard, so they cannot keep a conversation going, and the novelty runs out fast." },
      { h: "AI companion toys", p: "The newest category, and the one with the loudest warnings. [Common Sense Media's January 2026 assessment](https://institute.commonsensemedia.org/risk-assessments/ai-toys) found that more than a quarter of the replies its testers logged were inappropriate, and advised against giving one to any child of five or under. Whether a particular AI toy belongs in this bucket or the next depends entirely on how it was built, and the [checks that tell you which are here](/stories/what-to-look-for-in-a-safe-ai-toy)." },
      { h: "Kheelu", p: `[Kheelu](/products/kheelu) is built to be the listening kind on purpose: it understands what your child says, answers from a closed library rather than the open internet, then asks the next question, in ${LANGUAGES_LINE}, with up to ten languages at launch, and every word readable in the parent app. Open conversation runs on your home WiFi; Story mode and Bluetooth music work offline.` },
      { h: "A short checklist for any talking toy", p: "If you are choosing a talking toy for a child under five, ask five things. Does it reply, or only repeat? Does it ask questions back? Does it speak your home language? Can you read afterwards what it said? And does it work without a screen in the room? Then put one more question to anything that calls itself interactive: can it answer something it has never heard before? A button toy cannot. A repeat toy cannot. Only a toy that understands speech and forms a reply can, and until recently that did not exist at toy prices." },
      { p: `If your house has a bored cactus in it, pre-orders are open, and a refundable ${TOKEN_PRICE} holds your place.` },
    ],
    sources: [
      { label: "Harvard University, Center on the Developing Child: Serve and return", url: "https://developingchild.harvard.edu/key-concept/serve-and-return/" },
      { label: "Romeo and colleagues: Beyond the 30-Million-Word Gap, children's conversational exposure and language-related brain function (Psychological Science, 2018)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5945324/" },
      { label: "American Academy of Pediatrics: Media and Young Minds, policy statement (Pediatrics, 2016)", url: "https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds" },
      { label: "Common Sense Media, Youth AI Safety Institute: AI Toys risk assessment (January 2026)", url: "https://institute.commonsensemedia.org/risk-assessments/ai-toys" },
    ],
  },
  {
    slug: "screen-time-rules-parents-swear-by",
    title: "The 3-6-9-12 rule, and other screen rules parents swear by",
    description:
      "What is the 3-6-9-12 rule, where did it come from, and does it hold up? What the WHO, the Indian Academy of Pediatrics and the AAP say about screens under five.",
    theme: "Screen-free living",
    author: "Kashyap C.R",
    published: "2026-07-30",
    updated: "2026-09-05",
    pose: "grumpy",
    tint: "bg-yellow/15",
    hero: "/stories/screen-time-rules-parents-swear-by.jpg",
    heroAlt:
      "Two children laugh inside a blanket fort by torchlight while the television sits dark and a father watches from the doorway",
    paragraphs: [
      { p: "The 3-6-9-12 rule is four doorways for screens, proposed by the French psychiatrist Serge Tisseron in 2008: no screens before 3, no personal games console before 6, the internet with an adult from 9, and alone from 12. It is a framework, not a finding. Its first doorway is the one the strongest research agrees with." },
      { p: "Every parenting group has a moment where someone asks about screens and the replies fill with numbers. Follow 3-6-9-12. We do the one-hour rule. Have you tried 20-20-20. The rules travel fast because they are easy to remember, which is not the same as being true. Here is what each one actually says, where it comes from, and which ones deserve a place on your fridge." },
      { h: "Where does the 3-6-9-12 rule come from?", p: "Tisseron built the markers around four doorways in a child's life: starting nursery, starting school, reading and writing alone, and starting secondary school. The idea was to give parents a better question than how many hours. The question becomes: is my child ready for this kind of screen yet? He has since revised the later doorways on [his own site](https://www.3-6-9-12.org/), which tells you how to hold any rule of this kind. It is a starting point, not a law. The first doorway, no screens before three, is the part that has aged best, because it is the part the medical bodies agree with." },
      { h: "What do the WHO, the IAP and the AAP actually recommend?", p: "Three bodies have written this down, and they agree with each other more than the parent groups do. The [World Health Organization](https://www.ncbi.nlm.nih.gov/books/NBK541169/) says no sedentary screen time at all for one-year-olds, and no more than one hour a day for children aged 2 to 4, adding the three words that matter: less is better. The [Indian Academy of Pediatrics](https://pubmed.ncbi.nlm.nih.gov/34969943/), writing for Indian homes in 2022, says no screens below two years, at most one hour of supervised screen time a day from two to five, and under two hours a day from five to ten. The [American Academy of Pediatrics](https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds) lands in the same place for ages 2 to 5: about an hour a day of good content, watched together when you can." },
      { p: "Notice what all three do with the hour. They spend less of the page on the number and more on what the hour replaces. The worry is not the screen. It is the sleep, the running, the play, and above all the talking that a screen quietly eats. An hour of cartoons in a day full of conversation is a different thing from an hour of cartoons in a day of silence." },
      { h: "Is the one-hour rule enough on its own?", p: "The one-hour rule is the short version of those three guidelines, and it is the rule with the most evidence behind it. On its own it is a fence. What matters is the field inside it. The AAP adds three habits that turn the hour into something useful: choose slow, simple programmes over fast ones, watch together and talk about what you see, and do not let a screen become the only way to calm your child down. A cartoon you talk about together is closer to a conversation than to a screen." },
      { h: "What about 20-20-20?", p: "Every 20 minutes, look at something 20 feet away for 20 seconds. This one is about eyes, not development. It is sensible for anyone who reads on a screen, including you, and it says nothing about how much a three-year-old should watch. Keep it, but keep it in the right drawer." },
      { h: "Which rules have no source at all?", p: "You will also meet the 3-3-3 rule and the 7-7-7 rule, which mean something different in every post that mentions them. When a rule has no stable meaning and no author, treat it as a costume that folklore wears. You do not need it. The principles underneath every good rule fit in one sentence: less is better under five, together beats alone, and conversation is the thing screens quietly eat." },
      { h: "So which rule should our family keep?", p: "Pick the one you can actually hold. A rule kept loosely for a year beats a strict one abandoned by Thursday. If you want a single line for the fridge, take this one: under five, one hour at most, watched together, and never in the hour before bed. That is the WHO, the IAP and the AAP in one breath, and Tisseron would not argue with it. Our own plain-words read on the guidance is [here](/stories/how-much-screen-time-for-a-3-to-6-year-old)." },
      { p: `And if the hardest part is what fills the quiet after the screen goes off, that is the exact gap we built [Kheelu](/products/kheelu) for: a screen-free friend that talks, tells stories, and asks your child questions back. Pre-orders are open, and the ${TOKEN_PRICE} that holds your place comes back in full if you change your mind.` },
    ],
    sources: [
      { label: "World Health Organization: Guidelines on physical activity, sedentary behaviour and sleep for children under 5 years of age (2019)", url: "https://www.ncbi.nlm.nih.gov/books/NBK541169/" },
      { label: "Indian Academy of Pediatrics: Guidelines on screen time and digital wellness in infants, children and adolescents (Indian Pediatrics, 2022)", url: "https://pubmed.ncbi.nlm.nih.gov/34969943/" },
      { label: "American Academy of Pediatrics: Media and Young Minds, policy statement (Pediatrics, 2016)", url: "https://publications.aap.org/pediatrics/article/138/5/e20162591/60503/Media-and-Young-Minds" },
      { label: "Serge Tisseron: the 3-6-9-12 markers, on the author's own site (in French)", url: "https://www.3-6-9-12.org/" },
    ],
  },
  {
    slug: "talking-toys-and-late-talkers",
    ageNote:
      "Kheelu is built for children aged 3 and above. It is a toy that takes turns, not a treatment for speech delay. If you have concerns about your child's speech, a speech and language therapist is the right first call.",
    title: "Late talker? What helps a child find their words",
    description:
      "The waiting is hard, the advice is noisy, and the toys promise miracles. What actually moves the needle for a quiet two-year-old.",
    theme: "Talking together",
    author: "Ria Mangala Rewari",
    published: "2026-07-30",
    updated: "2026-09-05",
    pose: "sad",
    tint: "bg-blue/15",
    hero: "/stories/talking-toys-and-late-talkers.jpg",
    heroAlt:
      "A mother on a veranda points up at a bird on a wire while her young son looks up, mouth open, about to try the word",
    paragraphs: [
      { p: "Few silences are louder than a two-year-old who is not talking yet. Cousins the same age narrate their whole day, the family group chat fills with advice, and every toy in the shop suddenly claims to teach speech." },
      { p: "First, the reassuring truth: children start talking across a wide range of ages, and a late start is usually just that, a start that is late. The signal that matters is understanding. A child who follows what you say, points at things, and finds their own ways to tell you things is building language even while quiet. When understanding also seems behind, or gestures are missing, ask a paediatrician or a speech therapist, early and without embarrassment. Asking early never hurts. Waiting can." },
      { h: "What the research keeps saying", p: "Speech grows from the number of back and forth exchanges a child gets, not from the number of words spoken near them. Researchers call these conversational turns, and they matter more than flashcards, more than videos labelled educational, and far more than any toy. A turn can be tiny. The child points, you name it, they try the word, you smile and stretch it by one. That loop, repeated across ordinary days, is the engine." },
      { h: "Two myths worth dropping", p: "The first myth: a second home language causes speech delay. Speech researchers consistently find that it does not. A bilingual child may split their words across two languages for a while, and the total is what counts. Keep both languages. They are a gift, not a burden. The second myth: talking toys teach talking. A toy that repeats or plays phrases gives a child nothing to answer. If a toy joins the effort at all, it earns its place only by taking turns, answering, and asking something back." },
      { h: "What helps at home", p: "Narrate what you are doing in short sentences. Pause longer than feels natural, because a beginner needs time to load a word. Offer choices out loud, the red cup or the blue cup, so an answer is worth attempting. Sing, because melody carries words into memory. And switch off the background TV, which quietly eats the turns a room produces." },
      { p: "None of this needs a programme or a purchase. It needs turns, and anyone who loves the child can supply them." },
      { p: "Where a talking friend can honestly help is in adding turns when yours run out, and doing it in your home language. That is what we are building Kheelu to do, with every exchange staying readable by you. Pre-orders are open if you want one more voice in the room." },
    ],
  },
  {
    slug: "brain-development-toys-for-a-2-year-old",
    ageNote:
      "Kheelu is built for children aged 3 and above, so it is not the toy for a two-year-old today. The thinking above applies at any age, and Kheelu is there when your child turns 3.",
    title: "Brain development toys for a two-year-old: read this before the label",
    description:
      "Every box in the toy aisle promises cognitive growth. What a two-year-old brain actually builds with, and how to shop for it.",
    theme: "How children grow",
    author: "Apoorva Sahu",
    published: "2026-07-30",
    updated: "2026-09-05",
    pose: "joy",
    tint: "bg-orange/15",
    hero: "/stories/brain-development-toys-for-a-2-year-old.jpg",
    heroAlt:
      "A two-year-old claps with delight as a tower of wooden stacking cups topples on the living room floor",
    paragraphs: [
      { p: "Stand in any toy aisle and count the boxes that say brain development. Stacking cups promise it. Busy boards promise it. A plastic drum promises it. The phrase is doing a lot of work, and most of it is marketing." },
      { p: "Here is the version without a box: a two-year-old brain builds itself out of repetition, movement, and above all response. Things happen because the child did something, and someone noticed." },
      { h: "What actually earns the label", p: "Simple open toys do: blocks, cups, things that stack, pour, and fit inside each other. They earn it not because they are clever but because the child must be. A toy that does one loud thing when a button is pressed teaches the button. A toy that can become ten things teaches the child." },
      { h: "The ingredient no box lists", p: "The strongest finding in early development is that brains grow through serve and return, the loop where a child acts or asks and a person responds. No object on the shelf outranks a person on the floor. The same cups are twice the toy when someone counts the stack, asks which is biggest, and cheers the crash." },
      { p: "So the honest shopping rule for a two-year-old: fewer toys that perform, more toys that wait for the child to act. Check the safety mark, skip the promises, and spend the difference on time on the carpet." },
      { p: "Where does a talking toy fit that rule? Only if it responds rather than performs. A toy that answers a question and asks one back is doing the serve and return job. A toy that sings at the ceiling is furniture with batteries." },
      { p: "That is the bar we hold Kheelu to: it listens, answers, remembers, and moves at your child's pace, with no screen anywhere. If a friend on the carpet sounds better than another performing box, pre-orders are open." },
    ],
  },
];
